### ISSUE TITLE
bug: 在[测试demo](https://sakura.wrxinyue.org/)中的评论点赞显示问题

### ISSUE THREAD

**Issue by HypnosCicero** [WRXinYue/valaxy-theme-sakura#4]
# 步骤
1. 首先打开了[测试demo](https://sakura.wrxinyue.org/)，然后以游客的身份进入到了里面。
2. 然后我随意将页面下滑，翻到了[图片测试](https://sakura.wrxinyue.org/posts/test-images)
3. 以游客身份进行评论。
4. 前端显示了我的评论：
![image](https://github.com/WRXinYue/valaxy-theme-sakura/assets/67046501/e26c6735-fb8a-4ad6-bc14-6bd8dca8ad44)
5. 我对这条评论进行点赞

# 出现的效果：
1. 首先点赞的特效出现的很慢，可以排除是网络的因素，因为多次测试可以看到出现的速度都是一样的。
2. 我连续快速的多次点赞能将点赞数快速叠加起来；这个时候等待一些时间(目的是为了让点赞数显示)，然后再次点击则会取消点赞数。
![image-1](https://github.com/WRXinYue/valaxy-theme-sakura/assets/67046501/3cb7cb9a-d3d5-4042-bffd-4298d4c9d9de)
3. 同理在已经显示点赞的基础上连续点击也能去除掉多个点赞数。
![image-2](https://github.com/WRXinYue/valaxy-theme-sakura/assets/67046501/5ff8e348-0f89-49f5-90e5-0f50d4ebc151)

**Comment by WRXinYue** [comment]
在这个 [demo](https://sakura.wrxinyue.org/) 中, Waline 是使用 Vercel 进行部署的，涉及到其他静态资源的加载，可能对国内部分地区的用户可能不是很理想。所以您在使用的过程中可以使用国内服务器进行部署。Reaction 是为了轻量化设计，所以没有添加这些东西。数字本身只是为了营造氛围，无需太大做关注。关于 Waline 的更多信息，可以访问 [Waline 官网](https://waline.js.org/)。
