### ISSUE TITLE
A design question about footer navagation

### ISSUE THREAD

**Issue by furtherun** [WRXinYue/valaxy-theme-sakura#5]
## 关于页脚换页导航的“左右”问题

版本：`v0.6.0`

文章页面计算`NEXT ARTICLE`和`PREVIOUS ARTICLE`是根据主页的列表，但究竟是位于列表视图中上面的是Prev，还是下面的是Prev有些混乱。

### 例子

对于文章B来说，Next应当是A还是C？

```md
// home page article list
A
B
C
```

并且在文章页中，左侧为下一篇，右侧为上一篇，也与一般的操作习惯不符。

![image](https://github.com/WRXinYue/valaxy-theme-sakura/assets/47796426/41287d68-ade8-4975-99a9-327e7a05a798)

如上图[页面](https://sakura.wrxinyue.org/posts/theme-sakura)对比[さくら荘の白猫](https://2heng.xin/2021/07/30/flex-gap-polyfill-with-scss-mixins/)，按键位置相反，列表顺序相同；对比[云游君](https://yun.valaxy.site/posts/nested/z)，按键顺序和列表顺序都相反。

**Comment by WRXinYue** [comment]
已在[0.6.1](https://www.npmjs.com/package/valaxy-theme-sakura/v/0.6.1)版本修复
