### ISSUE TITLE
[bug]: SyntaxError: The requested module '/@id/__vite-optional-peer-dep:typewriter-effect/dist/core:valaxy-theme-sakura' does not provide an export named 'default'

### ISSUE THREAD

**Issue by MengXin001** [WRXinYue/valaxy-theme-sakura#6]
### Describe the bug
In release v0.6.1, it will broken with error like:
``` js
// theme/components/plugins/SakuraTypewriter.vue
SyntaxError: The requested module '/@id/__vite-optional-peer-dep:typewriter-effect/dist/core:valaxy-theme-sakura' does not provide an export named 'default' (at SakuraTypewriter.vue:14:8)
```
![image](https://github.com/WRXinYue/valaxy-theme-sakura/assets/54111871/fc8a0f71-459f-4b26-8673-fbf82e07060f)

### To Reproduce
1. Run `pnpm create valaxy`
2. Run `pnpm add valaxy-theme-sakura`
3. Configure some basic config in `valaxy.config.ts` (by the way, the example of `valaxy.config.ts` in README may needs to be updated)
4. Run `pnpm run dev`

it works well with the same config in v0.6.0.

**Comment by WRXinYue** [comment]
Thank you for raising the issue. An emergency release has been issued to fix it.
